apply plugin: 'maven-publish'
apply plugin: 'signing'
apply from: '../gradle/artifact-settings.gradle'
apply from: '../gradle/publish-root.gradle'

version = project.ext.versionName
group = project.ext.trackAsiaArtifactGroupId

afterEvaluate {
    publishing {
        publications {
            release(MavenPublication) {
                            
                groupId this.group
                artifactId project.ext.trackAsiaArtifactId

                from components.findByName('release')

                version this.version

                pom {
                    name = project.ext.trackAsiaArtifactTitle
                    description = project.ext.trackAsiaArtifactTitle
                    url = project.ext.trackAsiaArtifactUrl
                    licenses {
                        license {
                            name = project.ext.trackAsiaArtifactLicenseName
                            url = project.ext.trackAsiaArtifactLicenseUrl
                        }
                    }
                    developers {
                        developer {
                            id = project.ext.trackAsiaDeveloperId
                            name = project.ext.trackAsiaDeveloperName
                            email = 'trackasia@track-asia.com'
                        }
                    }
                    scm {
                        connection = project.ext.trackAsiaArtifactScmUrl
                        developerConnection = project.ext.trackAsiaArtifactScmUrl
                        url = project.ext.trackAsiaArtifactUrl
                    }
                }            
            }
        }
    }
}

signing {
    sign publishing.publications
}
